language: php

php:
  - 7.1
  - 7.2

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""
matrix:
  exclude:
  - php: 7.1
    env: COMPOSER_FLAGS="--prefer-lowest"
  - php: 7.2
    env: COMPOSER_FLAGS="--prefer-lowest"

before_script:
  - travis_retry mysql -e 'create database homestead;'
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
- cd application/tests
- vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
